import type { Ad } from "../types";

export const ADS: readonly Ad[] = [
  // Asana ads (comp-001) — 8 ads
  {
    id: "ad-001",
    competitorId: "comp-001",
    source: "google",
    headline: "Manage Projects at Scale — Asana Enterprise",
    description: "Stop chasing status updates. Asana gives your team a single source of truth for every project, goal, and workflow. Trusted by 85% of Fortune 100.",
    cta: "Get Started Free",
    landingUrl: "https://asana.com/enterprise",
    status: "active",
    firstSeenAt: "2026-01-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 28000,
  },
  {
    id: "ad-002",
    competitorId: "comp-001",
    source: "meta",
    headline: "Your Team Deserves Better Than Spreadsheets",
    description: "Asana replaces the chaos of email and spreadsheets with a clear, organized workspace. Try free for 30 days — no credit card required.",
    cta: "Try Free for 30 Days",
    landingUrl: "https://asana.com/teams",
    status: "active",
    firstSeenAt: "2026-02-01T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 19500,
  },
  {
    id: "ad-003",
    competitorId: "comp-001",
    source: "google",
    headline: "Project Management Software — 45% Off Annual Plans",
    description: "Limited time offer: get Asana Premium at 45% off when you upgrade today. Automate tasks, track goals, and ship projects faster.",
    cta: "Claim Your Discount",
    landingUrl: "https://asana.com/pricing",
    status: "active",
    firstSeenAt: "2026-02-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 34000,
  },
  {
    id: "ad-004",
    competitorId: "comp-001",
    source: "native",
    headline: "How 100,000+ Teams Ship Projects On Time",
    description: "See how companies like Amazon, Airbnb, and NASA use Asana to align their teams and deliver results. Download the free productivity playbook.",
    cta: "Download Free Guide",
    landingUrl: "https://asana.com/resources/productivity-guide",
    status: "active",
    firstSeenAt: "2026-01-28T00:00:00Z",
    lastSeenAt: "2026-03-01T00:00:00Z",
    estimatedSpendMonthly: 11200,
  },
  {
    id: "ad-005",
    competitorId: "comp-001",
    source: "google",
    headline: "Replace Monday.com — Free Migration Included",
    description: "Switching from Monday.com? Asana offers free data migration, dedicated onboarding, and a 25% discount for teams migrating from competitors.",
    cta: "Migrate for Free",
    landingUrl: "https://asana.com/monday-alternative",
    status: "paused",
    firstSeenAt: "2025-11-10T00:00:00Z",
    lastSeenAt: "2026-01-31T00:00:00Z",
    estimatedSpendMonthly: 22000,
  },
  {
    id: "ad-006",
    competitorId: "comp-001",
    source: "meta",
    headline: "See Why 5 Million Teams Choose Asana",
    description: "From startups to Fortune 500s, Asana helps teams move faster with AI-powered workflows, real-time reporting, and seamless integrations.",
    cta: "Start Free Trial",
    landingUrl: "https://asana.com/why-asana",
    status: "active",
    firstSeenAt: "2026-02-10T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 16800,
  },
  {
    id: "ad-007",
    competitorId: "comp-001",
    source: "google",
    headline: "Asana AI: Automate the Work Behind the Work",
    description: "Asana Intelligence learns your workflows and automates repetitive tasks so your team can focus on what actually matters. See it in action.",
    cta: "Watch Demo",
    landingUrl: "https://asana.com/ai",
    status: "active",
    firstSeenAt: "2026-02-25T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 41000,
  },
  {
    id: "ad-008",
    competitorId: "comp-001",
    source: "native",
    headline: "The Project Management Tool Built for Remote Teams",
    description: "Distributed teams thrive with Asana. Real-time collaboration, async updates, and timezone-aware scheduling built in.",
    cta: "Try Asana Free",
    landingUrl: "https://asana.com/remote-work",
    status: "ended",
    firstSeenAt: "2025-10-01T00:00:00Z",
    lastSeenAt: "2025-12-31T00:00:00Z",
    estimatedSpendMonthly: 8400,
  },

  // HubSpot ads (comp-002) — 8 ads
  {
    id: "ad-009",
    competitorId: "comp-002",
    source: "google",
    headline: "CRM Software Free Forever — HubSpot",
    description: "HubSpot's free CRM gives you everything you need to organize, track, and nurture your leads. Upgrade only when you're ready to scale.",
    cta: "Get Free CRM",
    landingUrl: "https://hubspot.com/crm",
    status: "active",
    firstSeenAt: "2026-01-10T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 52000,
  },
  {
    id: "ad-010",
    competitorId: "comp-002",
    source: "meta",
    headline: "Is Your CRM Slowing Down Your Sales Team?",
    description: "Sales reps waste 65% of their time on admin tasks. HubSpot automates the busywork so your team can focus on closing deals. Try free today.",
    cta: "Try Free Today",
    landingUrl: "https://hubspot.com/sales",
    status: "active",
    firstSeenAt: "2026-02-05T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 38000,
  },
  {
    id: "ad-011",
    competitorId: "comp-002",
    source: "google",
    headline: "HubSpot vs Salesforce — See the Difference",
    description: "Salesforce costs 3x more and takes months to set up. HubSpot deploys in days and your team will actually use it. Compare plans and pricing.",
    cta: "Compare Now",
    landingUrl: "https://hubspot.com/salesforce-alternative",
    status: "active",
    firstSeenAt: "2026-01-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 61000,
  },
  {
    id: "ad-012",
    competitorId: "comp-002",
    source: "native",
    headline: "How Casio Grew Leads by 328% With HubSpot",
    description: "Read the full case study: how Casio used HubSpot's marketing automation to triple their lead pipeline in 6 months. Get the playbook.",
    cta: "Read Case Study",
    landingUrl: "https://hubspot.com/case-studies/casio",
    status: "active",
    firstSeenAt: "2026-02-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 14500,
  },
  {
    id: "ad-013",
    competitorId: "comp-002",
    source: "meta",
    headline: "All-in-One Marketing Platform — Start Free",
    description: "Email, landing pages, ads, SEO, and analytics — all connected in one platform. Stop paying for 6 different tools. HubSpot does it all.",
    cta: "Start for Free",
    landingUrl: "https://hubspot.com/marketing",
    status: "active",
    firstSeenAt: "2026-02-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 29000,
  },
  {
    id: "ad-014",
    competitorId: "comp-002",
    source: "google",
    headline: "Marketing Automation That Actually Works",
    description: "Set up your first email sequence in 10 minutes. HubSpot's drag-and-drop automation is powerful enough for enterprise, simple enough for anyone.",
    cta: "Get Started Free",
    landingUrl: "https://hubspot.com/automation",
    status: "paused",
    firstSeenAt: "2025-12-01T00:00:00Z",
    lastSeenAt: "2026-02-15T00:00:00Z",
    estimatedSpendMonthly: 44000,
  },
  {
    id: "ad-015",
    competitorId: "comp-002",
    source: "google",
    headline: "HubSpot for Startups — 90% Off First Year",
    description: "Qualifying startups get up to 90% off HubSpot's full platform for the first year. Apply now and grow your business with enterprise-grade tools.",
    cta: "Apply Now",
    landingUrl: "https://hubspot.com/startups",
    status: "active",
    firstSeenAt: "2026-01-05T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 37000,
  },
  {
    id: "ad-016",
    competitorId: "comp-002",
    source: "native",
    headline: "The State of B2B Marketing in 2026 Report",
    description: "Download HubSpot's annual marketing report covering AI adoption, content trends, and revenue attribution. 3,200 marketers surveyed.",
    cta: "Download Report",
    landingUrl: "https://hubspot.com/state-of-marketing",
    status: "active",
    firstSeenAt: "2026-01-30T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 18000,
  },

  // Shopify ads (comp-003) — 8 ads
  {
    id: "ad-017",
    competitorId: "comp-003",
    source: "meta",
    headline: "Start Selling Online in Under 30 Minutes",
    description: "Shopify makes it easy to create a beautiful online store, manage inventory, process payments, and ship to customers worldwide. Try free for 3 days.",
    cta: "Start Free Trial",
    landingUrl: "https://shopify.com/start",
    status: "active",
    firstSeenAt: "2026-01-01T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 95000,
  },
  {
    id: "ad-018",
    competitorId: "comp-003",
    source: "google",
    headline: "Shopify — $1/Month for Your First 3 Months",
    description: "Limited time: launch your online store for just $1/month. Get everything you need to sell online, in person, and across social media channels.",
    cta: "Get Started for $1",
    landingUrl: "https://shopify.com/pricing",
    status: "active",
    firstSeenAt: "2026-02-01T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 115000,
  },
  {
    id: "ad-019",
    competitorId: "comp-003",
    source: "google",
    headline: "1.7 Million Merchants Trust Shopify to Power Their Business",
    description: "Join the world's most trusted e-commerce platform. Shopify powers brands of every size — from first-time entrepreneurs to billion-dollar enterprises.",
    cta: "Join Shopify",
    landingUrl: "https://shopify.com",
    status: "active",
    firstSeenAt: "2026-01-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 82000,
  },
  {
    id: "ad-020",
    competitorId: "comp-003",
    source: "meta",
    headline: "Sell Everywhere. Manage From One Place.",
    description: "Instagram, TikTok, Amazon, your own website — Shopify syncs your inventory and orders across every channel automatically. No more overselling.",
    cta: "Try It Free",
    landingUrl: "https://shopify.com/channels",
    status: "active",
    firstSeenAt: "2026-02-10T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 74000,
  },
  {
    id: "ad-021",
    competitorId: "comp-003",
    source: "native",
    headline: "How to Build a 6-Figure Store in 2026",
    description: "Discover the strategies top Shopify merchants use to scale past $100K. Free guide includes store setup, marketing playbook, and product research tactics.",
    cta: "Get Free Guide",
    landingUrl: "https://shopify.com/blog/six-figure-store",
    status: "active",
    firstSeenAt: "2026-01-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 31000,
  },
  {
    id: "ad-022",
    competitorId: "comp-003",
    source: "google",
    headline: "Shopify POS — Sell In-Store and Online Together",
    description: "Unify your retail and e-commerce with Shopify POS. Manage inventory, customer data, and sales from a single dashboard.",
    cta: "Explore Shopify POS",
    landingUrl: "https://shopify.com/pos",
    status: "paused",
    firstSeenAt: "2025-10-15T00:00:00Z",
    lastSeenAt: "2026-01-31T00:00:00Z",
    estimatedSpendMonthly: 55000,
  },
  {
    id: "ad-023",
    competitorId: "comp-003",
    source: "meta",
    headline: "Already Have a Store? Switch to Shopify — We'll Help",
    description: "Migrating from WooCommerce, Etsy, or BigCommerce? Our dedicated migration team will move your products, customers, and orders. Free for qualifying merchants.",
    cta: "Migrate for Free",
    landingUrl: "https://shopify.com/migrate",
    status: "active",
    firstSeenAt: "2026-02-05T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 68000,
  },
  {
    id: "ad-024",
    competitorId: "comp-003",
    source: "native",
    headline: "Shopify Capital: Get Up to $2M to Grow Your Store",
    description: "Eligible Shopify merchants can access fast, flexible funding based on their sales history. No lengthy bank applications. Funds arrive in as little as 2 days.",
    cta: "Check Your Offer",
    landingUrl: "https://shopify.com/capital",
    status: "active",
    firstSeenAt: "2026-01-25T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 42000,
  },

  // Stripe ads (comp-004) — 6 ads
  {
    id: "ad-025",
    competitorId: "comp-004",
    source: "google",
    headline: "Accept Payments Online — Stripe Developer Platform",
    description: "Stripe's APIs let you build and scale any payment flow. Cards, wallets, bank transfers, crypto — accept anything in 135+ currencies.",
    cta: "Start Building",
    landingUrl: "https://stripe.com/payments",
    status: "active",
    firstSeenAt: "2026-01-10T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 48000,
  },
  {
    id: "ad-026",
    competitorId: "comp-004",
    source: "google",
    headline: "Stripe for SaaS — Recurring Billing Made Simple",
    description: "Launch subscriptions in minutes. Stripe Billing handles dunning, proration, free trials, and revenue recognition so you don't have to.",
    cta: "Explore Stripe Billing",
    landingUrl: "https://stripe.com/billing",
    status: "active",
    firstSeenAt: "2026-01-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 35000,
  },
  {
    id: "ad-027",
    competitorId: "comp-004",
    source: "native",
    headline: "The Infrastructure Behind 1 Million+ Businesses",
    description: "From startups to Amazon, businesses choose Stripe for its reliability, speed, and developer experience. See what's possible with the Stripe platform.",
    cta: "See the Platform",
    landingUrl: "https://stripe.com/enterprise",
    status: "active",
    firstSeenAt: "2026-02-01T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 22000,
  },
  {
    id: "ad-028",
    competitorId: "comp-004",
    source: "google",
    headline: "Stripe Connect — Marketplace and Platform Payments",
    description: "Build a marketplace like Uber or Airbnb with Stripe Connect. Onboard sellers, split payments, and handle compliance in 50+ countries.",
    cta: "Build Your Marketplace",
    landingUrl: "https://stripe.com/connect",
    status: "active",
    firstSeenAt: "2026-02-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 41000,
  },
  {
    id: "ad-029",
    competitorId: "comp-004",
    source: "native",
    headline: "Stripe Radar: Stop Fraud Before It Costs You",
    description: "Stripe Radar uses machine learning trained on billions of transactions to block fraud while approving legitimate payments. Average false positive rate under 0.1%.",
    cta: "Learn About Radar",
    landingUrl: "https://stripe.com/radar",
    status: "paused",
    firstSeenAt: "2025-11-01T00:00:00Z",
    lastSeenAt: "2026-02-01T00:00:00Z",
    estimatedSpendMonthly: 18000,
  },
  {
    id: "ad-030",
    competitorId: "comp-004",
    source: "google",
    headline: "Lower Payment Processing Costs With Stripe",
    description: "Stripe's transparent pricing starts at 2.9% + 30 cents per transaction. No setup fees, no monthly fees, no hidden charges. Start accepting payments today.",
    cta: "View Pricing",
    landingUrl: "https://stripe.com/pricing",
    status: "active",
    firstSeenAt: "2026-01-05T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 29000,
  },

  // Notion ads (comp-005) — 6 ads
  {
    id: "ad-031",
    competitorId: "comp-005",
    source: "google",
    headline: "One App to Replace Them All — Notion",
    description: "Stop paying for Confluence, Evernote, Trello, and Google Docs separately. Notion combines notes, docs, databases, and project management in one workspace.",
    cta: "Try Notion Free",
    landingUrl: "https://notion.so",
    status: "active",
    firstSeenAt: "2026-01-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 32000,
  },
  {
    id: "ad-032",
    competitorId: "comp-005",
    source: "meta",
    headline: "Your Team's Second Brain — Try Notion",
    description: "Notion is the connected workspace where teams create, share, and organize their most important work. Used by teams at Nike, Figma, and Airbnb.",
    cta: "Start for Free",
    landingUrl: "https://notion.so/teams",
    status: "active",
    firstSeenAt: "2026-02-01T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 24000,
  },
  {
    id: "ad-033",
    competitorId: "comp-005",
    source: "meta",
    headline: "Notion AI: Write Faster, Think Clearer",
    description: "Notion AI drafts documents, summarizes meetings, fills in your databases, and translates — all inside your existing workspace. Try it free.",
    cta: "Try Notion AI",
    landingUrl: "https://notion.so/product/ai",
    status: "active",
    firstSeenAt: "2026-02-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 28000,
  },
  {
    id: "ad-034",
    competitorId: "comp-005",
    source: "google",
    headline: "Notion for Students — Free Education Plan",
    description: "Students and educators get Notion's Personal Pro plan completely free. Build your course notes, research database, and portfolio in one place.",
    cta: "Get Free Plan",
    landingUrl: "https://notion.so/students",
    status: "paused",
    firstSeenAt: "2025-08-15T00:00:00Z",
    lastSeenAt: "2025-12-31T00:00:00Z",
    estimatedSpendMonthly: 15000,
  },
  {
    id: "ad-035",
    competitorId: "comp-005",
    source: "native",
    headline: "The Wiki Your Team Will Actually Use",
    description: "Most team wikis get abandoned within 3 months. Notion's flexible structure and beautiful design keep teams coming back to update and reference docs.",
    cta: "See How It Works",
    landingUrl: "https://notion.so/use-case/wiki",
    status: "active",
    firstSeenAt: "2026-01-25T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 11500,
  },
  {
    id: "ad-036",
    competitorId: "comp-005",
    source: "google",
    headline: "Notion Sites — Build a Website Without Code",
    description: "Turn any Notion page into a public website in seconds. Perfect for portfolios, product docs, landing pages, and company blogs.",
    cta: "Create Your Site",
    landingUrl: "https://notion.so/sites",
    status: "active",
    firstSeenAt: "2026-02-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 19000,
  },

  // Figma ads (comp-006) — 6 ads
  {
    id: "ad-037",
    competitorId: "comp-006",
    source: "google",
    headline: "Design Together, Ship Faster — Figma",
    description: "Figma is the collaborative design tool used by 10 million people. Design, prototype, and hand off to developers — all in one browser-based platform.",
    cta: "Try Figma Free",
    landingUrl: "https://figma.com",
    status: "active",
    firstSeenAt: "2026-01-10T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 27000,
  },
  {
    id: "ad-038",
    competitorId: "comp-006",
    source: "meta",
    headline: "From Idea to Prototype in Minutes — Figma",
    description: "Figma's components, auto-layout, and prototyping tools let you go from whiteboard sketch to interactive prototype faster than ever.",
    cta: "Start Designing",
    landingUrl: "https://figma.com/prototyping",
    status: "active",
    firstSeenAt: "2026-02-05T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 19000,
  },
  {
    id: "ad-039",
    competitorId: "comp-006",
    source: "google",
    headline: "Figma for Teams — Real-Time Design Collaboration",
    description: "See your teammates' cursors in real time. No more \"final_FINAL_v3\" files. Figma keeps everyone on the latest version automatically.",
    cta: "Try Teams Plan",
    landingUrl: "https://figma.com/teams",
    status: "active",
    firstSeenAt: "2026-01-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 22000,
  },
  {
    id: "ad-040",
    competitorId: "comp-006",
    source: "native",
    headline: "Figma Dev Mode: The Bridge Between Design and Code",
    description: "Dev Mode gives developers accurate measurements, code snippets, and asset exports directly from design files. No more back-and-forth.",
    cta: "Explore Dev Mode",
    landingUrl: "https://figma.com/dev-mode",
    status: "active",
    firstSeenAt: "2026-02-10T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 9500,
  },
  {
    id: "ad-041",
    competitorId: "comp-006",
    source: "meta",
    headline: "Figma vs Adobe XD — Here's the Difference",
    description: "Adobe XD is going offline. Thousands of designers are moving to Figma. See why Figma is the industry standard and how to migrate your XD files.",
    cta: "Make the Switch",
    landingUrl: "https://figma.com/xd-alternative",
    status: "ended",
    firstSeenAt: "2025-09-01T00:00:00Z",
    lastSeenAt: "2025-12-15T00:00:00Z",
    estimatedSpendMonthly: 31000,
  },
  {
    id: "ad-042",
    competitorId: "comp-006",
    source: "google",
    headline: "Figma Config 2026 — Free Virtual Tickets Available",
    description: "Join 50,000+ designers at Figma's annual design conference. Three days of sessions, workshops, and product announcements. Register now.",
    cta: "Register Free",
    landingUrl: "https://figma.com/config",
    status: "active",
    firstSeenAt: "2026-02-28T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 14000,
  },

  // Slack ads (comp-007) — 7 ads
  {
    id: "ad-043",
    competitorId: "comp-007",
    source: "google",
    headline: "Where Work Happens — Slack",
    description: "Slack brings your team, your tools, and your information together. Search across all your conversations and files. Integrate with 2,600+ apps.",
    cta: "Try Slack Free",
    landingUrl: "https://slack.com",
    status: "active",
    firstSeenAt: "2026-01-05T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 58000,
  },
  {
    id: "ad-044",
    competitorId: "comp-007",
    source: "meta",
    headline: "Tired of Email Threads? There's a Better Way.",
    description: "Email kills productivity. Slack channels keep conversations organized, searchable, and focused. Your team will thank you. Start free today.",
    cta: "Get Slack Free",
    landingUrl: "https://slack.com/why-slack",
    status: "active",
    firstSeenAt: "2026-02-01T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 42000,
  },
  {
    id: "ad-045",
    competitorId: "comp-007",
    source: "google",
    headline: "Slack Enterprise Grid — For Companies of 1,000+",
    description: "Enterprise Grid gives large organizations centralized security, compliance controls, and admin tools while keeping teams in their own focused workspaces.",
    cta: "Contact Sales",
    landingUrl: "https://slack.com/enterprise",
    status: "active",
    firstSeenAt: "2026-01-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 71000,
  },
  {
    id: "ad-046",
    competitorId: "comp-007",
    source: "native",
    headline: "Slack AI: Ask Questions About Your Work History",
    description: "Slack AI lets you ask natural language questions about your team's conversations and get instant summaries. Find decisions made months ago in seconds.",
    cta: "Try Slack AI",
    landingUrl: "https://slack.com/ai",
    status: "active",
    firstSeenAt: "2026-02-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 33000,
  },
  {
    id: "ad-047",
    competitorId: "comp-007",
    source: "google",
    headline: "Slack vs Microsoft Teams — Which Is Right for You?",
    description: "Compare Slack and Teams on integrations, search, pricing, and usability. See why developers, startups, and creative teams choose Slack.",
    cta: "Compare Now",
    landingUrl: "https://slack.com/teams-alternative",
    status: "active",
    firstSeenAt: "2026-01-25T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 55000,
  },
  {
    id: "ad-048",
    competitorId: "comp-007",
    source: "meta",
    headline: "Slack Huddles: Instant Audio and Video for Your Team",
    description: "Drop into a quick Slack Huddle with video, screen sharing, and live captions. No meeting invite required. Just click and talk.",
    cta: "Start a Huddle",
    landingUrl: "https://slack.com/huddles",
    status: "paused",
    firstSeenAt: "2025-12-10T00:00:00Z",
    lastSeenAt: "2026-02-10T00:00:00Z",
    estimatedSpendMonthly: 27000,
  },
  {
    id: "ad-049",
    competitorId: "comp-007",
    source: "native",
    headline: "The Async-First Guide to Remote Team Management",
    description: "How top remote-first companies run effective teams without back-to-back meetings. Free guide from Slack featuring best practices from Stripe, Automattic, and GitHub.",
    cta: "Download Guide",
    landingUrl: "https://slack.com/resources/async-guide",
    status: "active",
    firstSeenAt: "2026-02-10T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 16500,
  },

  // Zoom ads (comp-008) — 7 ads
  {
    id: "ad-050",
    competitorId: "comp-008",
    source: "google",
    headline: "Zoom — Now With AI Companion Included Free",
    description: "Zoom AI Companion summarizes your meetings, writes follow-up emails, and helps you catch up on what you missed. Included in all paid plans at no extra cost.",
    cta: "Try Zoom Free",
    landingUrl: "https://zoom.us/ai-companion",
    status: "active",
    firstSeenAt: "2026-01-10T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 67000,
  },
  {
    id: "ad-051",
    competitorId: "comp-008",
    source: "meta",
    headline: "Host Webinars for Up to 50,000 Attendees — Zoom",
    description: "Zoom Webinars lets you run large-scale virtual events with registration, Q&A, polls, and analytics. Trusted by the world's leading events teams.",
    cta: "Start Your Webinar",
    landingUrl: "https://zoom.us/webinar",
    status: "active",
    firstSeenAt: "2026-01-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 49000,
  },
  {
    id: "ad-052",
    competitorId: "comp-008",
    source: "google",
    headline: "Zoom Phone — Cloud Phone System for Modern Teams",
    description: "Replace your legacy PBX with Zoom Phone. HD voice, call routing, voicemail transcription, and seamless handoff to Zoom Meetings.",
    cta: "Explore Zoom Phone",
    landingUrl: "https://zoom.us/phone",
    status: "active",
    firstSeenAt: "2026-02-05T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 55000,
  },
  {
    id: "ad-053",
    competitorId: "comp-008",
    source: "native",
    headline: "Zoom Contact Center: Transform Your Customer Experience",
    description: "Zoom Contact Center brings AI-powered customer service to video, chat, and voice in one unified platform. Reduce handle times by 40%.",
    cta: "See a Demo",
    landingUrl: "https://zoom.us/contact-center",
    status: "active",
    firstSeenAt: "2026-02-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 38000,
  },
  {
    id: "ad-054",
    competitorId: "comp-008",
    source: "google",
    headline: "Zoom for Education — 40% Off for Schools",
    description: "Schools and universities get special pricing on Zoom. End-to-end encryption, waiting rooms, and LMS integrations built for the classroom.",
    cta: "Get Education Pricing",
    landingUrl: "https://zoom.us/education",
    status: "paused",
    firstSeenAt: "2025-08-01T00:00:00Z",
    lastSeenAt: "2025-12-31T00:00:00Z",
    estimatedSpendMonthly: 31000,
  },
  {
    id: "ad-055",
    competitorId: "comp-008",
    source: "meta",
    headline: "Zoom Rooms: Transform Any Space Into a Meeting Room",
    description: "Zoom Rooms turns any conference room into a smart collaboration space. One-touch join, wireless sharing, and AI-powered noise cancellation.",
    cta: "Learn About Zoom Rooms",
    landingUrl: "https://zoom.us/rooms",
    status: "active",
    firstSeenAt: "2026-01-30T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 44000,
  },
  {
    id: "ad-056",
    competitorId: "comp-008",
    source: "native",
    headline: "Future of Work Report 2026 — Hybrid Teams",
    description: "Zoom's annual report on hybrid work trends: AI adoption, meeting fatigue solutions, and how top companies structure their hybrid workplace.",
    cta: "Download Free",
    landingUrl: "https://zoom.us/resources/future-of-work",
    status: "active",
    firstSeenAt: "2026-02-25T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 21000,
  },

  // Airtable ads (comp-009) — 5 ads
  {
    id: "ad-057",
    competitorId: "comp-009",
    source: "google",
    headline: "Build the App Your Business Actually Needs — Airtable",
    description: "Airtable lets non-technical teams build custom databases, workflows, and dashboards without code. It's the spreadsheet that thinks like a database.",
    cta: "Try Airtable Free",
    landingUrl: "https://airtable.com",
    status: "active",
    firstSeenAt: "2026-01-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 26000,
  },
  {
    id: "ad-058",
    competitorId: "comp-009",
    source: "meta",
    headline: "Airtable: The Database Your Marketing Team Will Love",
    description: "Track campaigns, assets, and approvals in one connected workspace. Airtable syncs with Google Drive, Slack, and 600+ other tools your team already uses.",
    cta: "Start Free",
    landingUrl: "https://airtable.com/solutions/marketing",
    status: "active",
    firstSeenAt: "2026-02-01T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 19000,
  },
  {
    id: "ad-059",
    competitorId: "comp-009",
    source: "google",
    headline: "Replace Excel and Access With Airtable",
    description: "Airtable combines the familiarity of a spreadsheet with the power of a relational database. Collaborative, real-time, and works in your browser.",
    cta: "See the Demo",
    landingUrl: "https://airtable.com/product",
    status: "active",
    firstSeenAt: "2026-01-10T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 22000,
  },
  {
    id: "ad-060",
    competitorId: "comp-009",
    source: "native",
    headline: "How Netflix Uses Airtable to Manage Content Production",
    description: "See the Airtable workflow behind Netflix's global content pipeline. Case study includes templates you can copy for your own creative team.",
    cta: "Read Case Study",
    landingUrl: "https://airtable.com/case-studies/netflix",
    status: "active",
    firstSeenAt: "2026-02-10T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 9800,
  },
  {
    id: "ad-061",
    competitorId: "comp-009",
    source: "meta",
    headline: "Airtable AI: Turn Your Data Into Insights Automatically",
    description: "Airtable AI categorizes records, writes summaries, and generates insights from your data — no SQL required. Upgrade to any paid plan to unlock it.",
    cta: "Try Airtable AI",
    landingUrl: "https://airtable.com/ai",
    status: "paused",
    firstSeenAt: "2026-01-05T00:00:00Z",
    lastSeenAt: "2026-02-20T00:00:00Z",
    estimatedSpendMonthly: 14000,
  },

  // Calendly ads (comp-010) — 5 ads
  {
    id: "ad-062",
    competitorId: "comp-010",
    source: "google",
    headline: "Eliminate the Back-and-Forth — Calendly",
    description: "Share your Calendly link and let invitees choose a time that works. Automatically syncs with Google Calendar, Outlook, and your CRM.",
    cta: "Get Started Free",
    landingUrl: "https://calendly.com",
    status: "active",
    firstSeenAt: "2026-01-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 18000,
  },
  {
    id: "ad-063",
    competitorId: "comp-010",
    source: "meta",
    headline: "Book More Demos. Close More Deals. Use Calendly.",
    description: "Sales teams using Calendly see 2x more demos booked and 40% faster time-to-meeting. Connect with HubSpot, Salesforce, and your video platform.",
    cta: "Try Free for Sales",
    landingUrl: "https://calendly.com/sales",
    status: "active",
    firstSeenAt: "2026-02-05T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 14000,
  },
  {
    id: "ad-064",
    competitorId: "comp-010",
    source: "google",
    headline: "Calendly for Teams — Round-Robin Scheduling",
    description: "Route meetings to the right team member automatically with round-robin scheduling. Perfect for sales teams, support queues, and customer success.",
    cta: "Try Teams Free",
    landingUrl: "https://calendly.com/teams",
    status: "active",
    firstSeenAt: "2026-01-25T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 21000,
  },
  {
    id: "ad-065",
    competitorId: "comp-010",
    source: "native",
    headline: "Stop Losing Leads to Slow Follow-Up",
    description: "87% of leads go with whoever responds first. Calendly lets hot leads book a meeting instantly from your website. No human required to schedule.",
    cta: "Add to Your Website",
    landingUrl: "https://calendly.com/integrations/website",
    status: "active",
    firstSeenAt: "2026-02-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 9500,
  },
  {
    id: "ad-066",
    competitorId: "comp-010",
    source: "meta",
    headline: "Calendly Routing Forms — Qualify Leads Before They Book",
    description: "Ask qualifying questions before someone books. Route to different meeting types or team members based on their answers. Works with any CRM.",
    cta: "Explore Routing Forms",
    landingUrl: "https://calendly.com/routing",
    status: "paused",
    firstSeenAt: "2025-11-15T00:00:00Z",
    lastSeenAt: "2026-01-31T00:00:00Z",
    estimatedSpendMonthly: 11000,
  },

  // Intercom ads (comp-011) — 6 ads
  {
    id: "ad-067",
    competitorId: "comp-011",
    source: "google",
    headline: "Customer Support Powered by AI — Intercom",
    description: "Intercom Fin AI resolves 50%+ of support questions without human agents. Built on GPT-4. Integrates with your help center and CRM.",
    cta: "See Fin in Action",
    landingUrl: "https://intercom.com/ai",
    status: "active",
    firstSeenAt: "2026-01-10T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 44000,
  },
  {
    id: "ad-068",
    competitorId: "comp-011",
    source: "meta",
    headline: "Reduce Support Costs by 40% — Intercom",
    description: "Teams using Intercom's AI-powered inbox resolve tickets 3x faster and with 40% less headcount. See the ROI calculator and find your savings.",
    cta: "Calculate Your Savings",
    landingUrl: "https://intercom.com/roi",
    status: "active",
    firstSeenAt: "2026-02-01T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 31000,
  },
  {
    id: "ad-069",
    competitorId: "comp-011",
    source: "google",
    headline: "Intercom vs Zendesk — Why Teams Are Switching",
    description: "Zendesk is expensive and outdated. Intercom's AI-first platform is faster to set up, easier for agents, and delivers higher CSAT scores.",
    cta: "See the Comparison",
    landingUrl: "https://intercom.com/zendesk-alternative",
    status: "active",
    firstSeenAt: "2026-01-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 52000,
  },
  {
    id: "ad-070",
    competitorId: "comp-011",
    source: "native",
    headline: "The Customer Service AI Benchmark Report 2026",
    description: "How are companies actually deploying AI in customer service? Intercom surveyed 1,000 support leaders to find out. Download the full report.",
    cta: "Get the Report",
    landingUrl: "https://intercom.com/resources/ai-benchmark",
    status: "active",
    firstSeenAt: "2026-02-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 18000,
  },
  {
    id: "ad-071",
    competitorId: "comp-011",
    source: "meta",
    headline: "Proactive Support: Solve Problems Before They Start",
    description: "Intercom identifies at-risk customers based on product usage and triggers personalized outreach automatically. Reduce churn before customers even reach out.",
    cta: "Book a Demo",
    landingUrl: "https://intercom.com/proactive-support",
    status: "paused",
    firstSeenAt: "2025-12-01T00:00:00Z",
    lastSeenAt: "2026-02-15T00:00:00Z",
    estimatedSpendMonthly: 24000,
  },
  {
    id: "ad-072",
    competitorId: "comp-011",
    source: "google",
    headline: "Intercom for Startups — 95% Off First Year",
    description: "Early-stage startups get Intercom's full platform at 95% off for the first year. Apply with your Y Combinator, Techstars, or other accelerator affiliation.",
    cta: "Apply for Startup Discount",
    landingUrl: "https://intercom.com/startups",
    status: "active",
    firstSeenAt: "2026-01-05T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 29000,
  },

  // Drift ads (comp-012) — 5 ads
  {
    id: "ad-073",
    competitorId: "comp-012",
    source: "google",
    headline: "Conversational Marketing That Converts — Drift",
    description: "Drift's AI chatbots engage website visitors 24/7, qualify leads, and book meetings automatically. See a 30%+ lift in pipeline from your existing traffic.",
    cta: "Get a Demo",
    landingUrl: "https://drift.com",
    status: "active",
    firstSeenAt: "2026-01-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 14000,
  },
  {
    id: "ad-074",
    competitorId: "comp-012",
    source: "meta",
    headline: "Stop Making Buyers Fill Out Forms",
    description: "Forms kill momentum. Drift lets buyers start a conversation instantly from any page. AI qualifies them and routes to the right rep in real time.",
    cta: "Try Drift Free",
    landingUrl: "https://drift.com/why-drift",
    status: "active",
    firstSeenAt: "2026-02-01T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 10500,
  },
  {
    id: "ad-075",
    competitorId: "comp-012",
    source: "google",
    headline: "Drift Bionic Chatbots: AI That Sounds Human",
    description: "Drift's Bionic Chatbots combine AI and human knowledge to have natural conversations, answer complex questions, and hand off seamlessly to live reps.",
    cta: "See It in Action",
    landingUrl: "https://drift.com/bionic-chatbots",
    status: "active",
    firstSeenAt: "2026-01-25T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 12000,
  },
  {
    id: "ad-076",
    competitorId: "comp-012",
    source: "native",
    headline: "Drift Fastlane: Priority Routing for Your Best Accounts",
    description: "Identify target accounts visiting your site and fast-track them directly to your sales team. ABM-powered engagement built into Drift.",
    cta: "Learn About Fastlane",
    landingUrl: "https://drift.com/fastlane",
    status: "ended",
    firstSeenAt: "2025-10-01T00:00:00Z",
    lastSeenAt: "2025-12-31T00:00:00Z",
    estimatedSpendMonthly: 8000,
  },
  {
    id: "ad-077",
    competitorId: "comp-012",
    source: "meta",
    headline: "Your Pipeline Is Leaking. Here's How to Fix It.",
    description: "Most B2B websites convert less than 2% of visitors. Drift customers see 3-5x conversion improvements by replacing forms with conversations.",
    cta: "Fix Your Pipeline",
    landingUrl: "https://drift.com/pipeline",
    status: "active",
    firstSeenAt: "2026-02-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 9000,
  },

  // Additional cross-competitor ads to reach 80+
  {
    id: "ad-078",
    competitorId: "comp-001",
    source: "google",
    headline: "Asana Goals: Connect Team Work to Company OKRs",
    description: "Link every project and task to company objectives. See real-time progress toward OKRs and surface blockers before they become problems.",
    cta: "Explore Goals",
    landingUrl: "https://asana.com/goals",
    status: "active",
    firstSeenAt: "2026-02-28T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 26000,
  },
  {
    id: "ad-079",
    competitorId: "comp-002",
    source: "google",
    headline: "HubSpot Payments — Accept Payments Inside Your CRM",
    description: "Send payment links in emails, proposals, and invoices. Get paid faster without switching between tools. Built natively into HubSpot.",
    cta: "Activate Payments",
    landingUrl: "https://hubspot.com/payments",
    status: "active",
    firstSeenAt: "2026-02-25T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 31000,
  },
  {
    id: "ad-080",
    competitorId: "comp-003",
    source: "google",
    headline: "Shopify Markets: Sell Globally Without the Complexity",
    description: "Expand to 200+ countries with localized currencies, languages, and tax handling. Shopify Markets makes going global simple.",
    cta: "Go Global",
    landingUrl: "https://shopify.com/markets",
    status: "active",
    firstSeenAt: "2026-02-20T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 89000,
  },
  {
    id: "ad-081",
    competitorId: "comp-007",
    source: "google",
    headline: "Slack Workflow Builder — Automate Without Code",
    description: "Build automated workflows that handle approvals, notifications, onboarding, and more — no engineering resources required.",
    cta: "Start Automating",
    landingUrl: "https://slack.com/workflow-builder",
    status: "active",
    firstSeenAt: "2026-02-10T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 38000,
  },
  {
    id: "ad-082",
    competitorId: "comp-008",
    source: "meta",
    headline: "Zoom Events: Virtual Event Platform for Up to 100K",
    description: "Run virtual conferences, summits, and expos with Zoom Events. Multi-session scheduling, sponsor booths, and attendee networking built in.",
    cta: "Plan Your Event",
    landingUrl: "https://zoom.us/events",
    status: "active",
    firstSeenAt: "2026-02-28T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 33000,
  },
  {
    id: "ad-083",
    competitorId: "comp-004",
    source: "google",
    headline: "Stripe Treasury — Embedded Finance for Your Platform",
    description: "Add bank accounts, cards, and financial services to your platform with Stripe Treasury. Launch financial products in days, not years.",
    cta: "Explore Treasury",
    landingUrl: "https://stripe.com/treasury",
    status: "active",
    firstSeenAt: "2026-02-15T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 27000,
  },
  {
    id: "ad-084",
    competitorId: "comp-005",
    source: "google",
    headline: "Notion Calendar — See Your Work and Your Schedule Together",
    description: "Notion Calendar connects your meetings, tasks, and docs into one unified view. Never lose track of context before an important call.",
    cta: "Try Notion Calendar",
    landingUrl: "https://notion.so/calendar",
    status: "active",
    firstSeenAt: "2026-03-01T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 22000,
  },
  {
    id: "ad-085",
    competitorId: "comp-011",
    source: "native",
    headline: "Intercom Messenger: In-App Support That Converts",
    description: "Embed Intercom in your web or mobile app to provide instant support and onboarding. Customers who get help in-app have 20% higher retention.",
    cta: "Install the Messenger",
    landingUrl: "https://intercom.com/messenger",
    status: "active",
    firstSeenAt: "2026-02-05T00:00:00Z",
    lastSeenAt: "2026-03-02T00:00:00Z",
    estimatedSpendMonthly: 17000,
  },
];
