import type { Alert } from "../types";

export const ALERTS: readonly Alert[] = [
  // new_competitor alerts (3)
  {
    id: "alert-001",
    type: "new_competitor",
    title: "New Competitor Detected: ClickUp",
    description: "clickup.com has entered the \"project management software\" keyword space and is running Google Search ads. Estimated starting budget: $45,000/month.",
    severity: "warning",
    isRead: false,
    competitorId: undefined,
    keywordId: "kw-001",
    createdAt: "2026-03-02T08:15:00Z",
    metadata: { domain: "clickup.com", detectedBudget: 45000, channel: "google" },
  },
  {
    id: "alert-002",
    type: "new_competitor",
    title: "New Competitor Detected: Monday.com",
    description: "monday.com launched a new Meta campaign targeting \"team collaboration tools\" with video creatives. First ads seen 2 days ago.",
    severity: "info",
    isRead: true,
    competitorId: undefined,
    keywordId: "kw-003",
    createdAt: "2026-03-01T14:30:00Z",
    metadata: { domain: "monday.com", detectedBudget: 32000, channel: "meta" },
  },
  {
    id: "alert-003",
    type: "new_competitor",
    title: "New Competitor Detected: Linear",
    description: "linear.app is running native ads and sponsoring newsletters targeting developers and engineering managers in your space.",
    severity: "info",
    isRead: true,
    competitorId: undefined,
    keywordId: undefined,
    createdAt: "2026-02-28T10:00:00Z",
    metadata: { domain: "linear.app", detectedBudget: 18000, channel: "native" },
  },

  // position_change alerts (5)
  {
    id: "alert-004",
    type: "position_change",
    title: "HubSpot Moved to Position #1 for \"crm for small business\"",
    description: "hubspot.com jumped from position #3 to position #1 on Google Search for \"crm for small business\". They increased ad spend by an estimated 35%.",
    severity: "critical",
    isRead: false,
    competitorId: "comp-002",
    keywordId: "kw-002",
    createdAt: "2026-03-02T16:45:00Z",
    metadata: { keyword: "crm for small business", oldPosition: 3, newPosition: 1, estimatedSpendIncrease: 0.35 },
  },
  {
    id: "alert-005",
    type: "position_change",
    title: "Asana Dropped to Position #4 for \"project management software\"",
    description: "asana.com fell from position #1 to #4 for \"project management software\" as Monday.com and ClickUp increased bids significantly this week.",
    severity: "warning",
    isRead: false,
    competitorId: "comp-001",
    keywordId: "kw-001",
    createdAt: "2026-03-02T12:00:00Z",
    metadata: { keyword: "project management software", oldPosition: 1, newPosition: 4, estimatedSpendChange: -0.20 },
  },
  {
    id: "alert-006",
    type: "position_change",
    title: "Shopify Gained Top Spot for \"online store builder\"",
    description: "shopify.com reclaimed the #1 position for \"online store builder\" after Wix briefly held it for 6 days.",
    severity: "info",
    isRead: true,
    competitorId: "comp-003",
    keywordId: "kw-029",
    createdAt: "2026-03-01T09:20:00Z",
    metadata: { keyword: "online store builder", oldPosition: 2, newPosition: 1 },
  },
  {
    id: "alert-007",
    type: "position_change",
    title: "Intercom Dropped for \"customer support software\"",
    description: "intercom.com fell from position #2 to #5 for \"customer support software\". Zendesk and Freshdesk both increased bids this week.",
    severity: "warning",
    isRead: false,
    competitorId: "comp-011",
    keywordId: "kw-007",
    createdAt: "2026-02-28T19:30:00Z",
    metadata: { keyword: "customer support software", oldPosition: 2, newPosition: 5 },
  },
  {
    id: "alert-008",
    type: "position_change",
    title: "Zoom Climbed to Position #1 for \"video conferencing software\"",
    description: "zoom.us secured the top position for \"video conferencing software\" on Google, displacing Microsoft Teams which held #1 for the past 3 weeks.",
    severity: "info",
    isRead: true,
    competitorId: "comp-008",
    keywordId: "kw-008",
    createdAt: "2026-02-27T11:15:00Z",
    metadata: { keyword: "video conferencing software", oldPosition: 2, newPosition: 1 },
  },

  // budget_spike alerts (4)
  {
    id: "alert-009",
    type: "budget_spike",
    title: "HubSpot Ad Spend Spiked 82% This Week",
    description: "hubspot.com's estimated monthly ad spend jumped from $395,000 to $720,000 — an 82% increase. New campaigns detected across Google Search, Display, and Meta.",
    severity: "critical",
    isRead: false,
    competitorId: "comp-002",
    keywordId: undefined,
    createdAt: "2026-03-02T20:00:00Z",
    metadata: { previousEstimate: 395000, newEstimate: 720000, percentageIncrease: 82, newCampaignsDetected: 7 },
  },
  {
    id: "alert-010",
    type: "budget_spike",
    title: "Shopify Increased Meta Budget by 45%",
    description: "shopify.com launched 12 new Meta video ads this week, driving an estimated 45% increase in their Meta ad spend. New creative themes: success stories and founder spotlights.",
    severity: "warning",
    isRead: false,
    competitorId: "comp-003",
    keywordId: undefined,
    createdAt: "2026-03-01T22:00:00Z",
    metadata: { previousEstimate: 860000, newEstimate: 1250000, percentageIncrease: 45, platform: "meta", newAdsLaunched: 12 },
  },
  {
    id: "alert-011",
    type: "budget_spike",
    title: "Slack Ad Spend Up 38% — New Enterprise Campaign",
    description: "slack.com launched a new enterprise-focused Google Search campaign targeting CIO and IT director keywords. Estimated spend increase: 38% week-over-week.",
    severity: "warning",
    isRead: true,
    competitorId: "comp-007",
    keywordId: undefined,
    createdAt: "2026-02-28T08:30:00Z",
    metadata: { previousEstimate: 390000, newEstimate: 540000, percentageIncrease: 38, platform: "google" },
  },
  {
    id: "alert-012",
    type: "budget_spike",
    title: "Figma Tripled Native Ad Spend",
    description: "figma.com launched a native advertising blitz across design and developer publications ahead of Config 2026. Spend estimated at 3x the previous month.",
    severity: "info",
    isRead: true,
    competitorId: "comp-006",
    keywordId: undefined,
    createdAt: "2026-02-27T15:45:00Z",
    metadata: { previousEstimate: 59000, newEstimate: 178000, percentageIncrease: 202, platform: "native" },
  },

  // new_keyword alerts (3)
  {
    id: "alert-013",
    type: "new_keyword",
    title: "HubSpot Started Bidding on \"ai crm software\"",
    description: "hubspot.com is now targeting \"ai crm software\" on Google Search — a keyword they had not previously appeared in. CPC average: $13.40. This keyword has 28,000 monthly searches.",
    severity: "warning",
    isRead: false,
    competitorId: "comp-002",
    keywordId: undefined,
    createdAt: "2026-03-02T18:00:00Z",
    metadata: { keyword: "ai crm software", searchVolume: 28000, cpcAvg: 13.40, competitor: "hubspot.com" },
  },
  {
    id: "alert-014",
    type: "new_keyword",
    title: "Asana Targeting \"monday.com alternative\" — Competitor Conquest",
    description: "asana.com launched a conquest campaign bidding on \"monday.com alternative\" keywords on Google. These ads link directly to Asana's Monday.com comparison landing page.",
    severity: "critical",
    isRead: false,
    competitorId: "comp-001",
    keywordId: undefined,
    createdAt: "2026-03-01T10:30:00Z",
    metadata: { keyword: "monday.com alternative", searchVolume: 41000, cpcAvg: 11.80, tactic: "conquest" },
  },
  {
    id: "alert-015",
    type: "new_keyword",
    title: "Stripe Entered \"buy payment software\" Market",
    description: "stripe.com began bidding on high-intent transactional keywords including \"buy payment software\" and \"payment processor sign up\". Combined volume: 35,000/month.",
    severity: "info",
    isRead: true,
    competitorId: "comp-004",
    keywordId: undefined,
    createdAt: "2026-02-26T14:00:00Z",
    metadata: { keywords: ["buy payment software", "payment processor sign up"], combinedVolume: 35000, cpcRange: "9.20-15.60" },
  },
];
