import type { AdAnalysis } from "../types";

export const AD_ANALYSES: readonly AdAnalysis[] = [
  { adId: "ad-001", headlineFormula: "Action + Benefit + Brand", emotionalTriggers: ["authority", "trust", "social_proof"], ctaType: "click", sentiment: "positive", uniquenessScore: 72, copyLength: 142 },
  { adId: "ad-002", headlineFormula: "Problem + Solution", emotionalTriggers: ["urgency", "aspiration", "trust"], ctaType: "click", sentiment: "positive", uniquenessScore: 65, copyLength: 131 },
  { adId: "ad-003", headlineFormula: "Urgency + Offer", emotionalTriggers: ["urgency", "scarcity", "fomo"], ctaType: "click", sentiment: "positive", uniquenessScore: 48, copyLength: 118 },
  { adId: "ad-004", headlineFormula: "Social Proof + CTA", emotionalTriggers: ["social_proof", "authority", "curiosity"], ctaType: "download", sentiment: "positive", uniquenessScore: 81, copyLength: 155 },
  { adId: "ad-005", headlineFormula: "Comparison + Offer", emotionalTriggers: ["urgency", "trust", "aspiration"], ctaType: "click", sentiment: "neutral", uniquenessScore: 55, copyLength: 129 },
  { adId: "ad-006", headlineFormula: "Number + Social Proof", emotionalTriggers: ["social_proof", "trust", "aspiration"], ctaType: "click", sentiment: "positive", uniquenessScore: 60, copyLength: 138 },
  { adId: "ad-007", headlineFormula: "Brand + Feature + Benefit", emotionalTriggers: ["curiosity", "aspiration", "authority"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 79, copyLength: 116 },
  { adId: "ad-008", headlineFormula: "Product Category + Audience + Benefit", emotionalTriggers: ["aspiration", "trust"], ctaType: "click", sentiment: "positive", uniquenessScore: 67, copyLength: 123 },

  { adId: "ad-009", headlineFormula: "Product + Price Anchor + Brand", emotionalTriggers: ["trust", "aspiration", "scarcity"], ctaType: "click", sentiment: "positive", uniquenessScore: 70, copyLength: 134 },
  { adId: "ad-010", headlineFormula: "Question + Solution", emotionalTriggers: ["fear", "urgency", "aspiration"], ctaType: "click", sentiment: "positive", uniquenessScore: 74, copyLength: 145 },
  { adId: "ad-011", headlineFormula: "Comparison + Differentiation", emotionalTriggers: ["curiosity", "trust", "authority"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 66, copyLength: 152 },
  { adId: "ad-012", headlineFormula: "Social Proof + Specific Number", emotionalTriggers: ["social_proof", "authority", "aspiration"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 85, copyLength: 148 },
  { adId: "ad-013", headlineFormula: "Aggregation + Price Anchor", emotionalTriggers: ["aspiration", "trust", "scarcity"], ctaType: "click", sentiment: "positive", uniquenessScore: 58, copyLength: 139 },
  { adId: "ad-014", headlineFormula: "Product Feature + Time Promise", emotionalTriggers: ["urgency", "trust", "curiosity"], ctaType: "click", sentiment: "positive", uniquenessScore: 63, copyLength: 128 },
  { adId: "ad-015", headlineFormula: "Audience Segment + Offer", emotionalTriggers: ["exclusivity", "scarcity", "aspiration"], ctaType: "click", sentiment: "positive", uniquenessScore: 77, copyLength: 126 },
  { adId: "ad-016", headlineFormula: "Content Offer + Authority Signal", emotionalTriggers: ["authority", "curiosity", "trust"], ctaType: "download", sentiment: "neutral", uniquenessScore: 82, copyLength: 112 },

  { adId: "ad-017", headlineFormula: "Action + Time Promise", emotionalTriggers: ["urgency", "aspiration", "trust"], ctaType: "click", sentiment: "positive", uniquenessScore: 55, copyLength: 144 },
  { adId: "ad-018", headlineFormula: "Brand + Irresistible Offer", emotionalTriggers: ["scarcity", "urgency", "fomo"], ctaType: "buy", sentiment: "positive", uniquenessScore: 45, copyLength: 133 },
  { adId: "ad-019", headlineFormula: "Number + Social Proof + Brand", emotionalTriggers: ["social_proof", "authority", "trust"], ctaType: "click", sentiment: "positive", uniquenessScore: 68, copyLength: 128 },
  { adId: "ad-020", headlineFormula: "Benefit + Solution", emotionalTriggers: ["aspiration", "trust", "authority"], ctaType: "click", sentiment: "positive", uniquenessScore: 73, copyLength: 136 },
  { adId: "ad-021", headlineFormula: "How-To + Aspiration Goal", emotionalTriggers: ["aspiration", "curiosity", "fomo"], ctaType: "download", sentiment: "positive", uniquenessScore: 78, copyLength: 151 },
  { adId: "ad-022", headlineFormula: "Product Name + Feature + Benefit", emotionalTriggers: ["authority", "trust"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 62, copyLength: 122 },
  { adId: "ad-023", headlineFormula: "Existing Customer + Offer", emotionalTriggers: ["trust", "urgency", "social_proof"], ctaType: "click", sentiment: "positive", uniquenessScore: 71, copyLength: 149 },
  { adId: "ad-024", headlineFormula: "Product + Large Number + Benefit", emotionalTriggers: ["aspiration", "authority", "curiosity"], ctaType: "click", sentiment: "positive", uniquenessScore: 83, copyLength: 138 },

  { adId: "ad-025", headlineFormula: "Action + Product Category + Brand", emotionalTriggers: ["authority", "trust", "aspiration"], ctaType: "click", sentiment: "positive", uniquenessScore: 69, copyLength: 126 },
  { adId: "ad-026", headlineFormula: "Audience + Benefit + Time Promise", emotionalTriggers: ["aspiration", "trust", "urgency"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 76, copyLength: 139 },
  { adId: "ad-027", headlineFormula: "Social Proof + Audience Range", emotionalTriggers: ["social_proof", "authority", "trust"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 74, copyLength: 131 },
  { adId: "ad-028", headlineFormula: "Product + Use Case", emotionalTriggers: ["aspiration", "curiosity", "authority"], ctaType: "click", sentiment: "positive", uniquenessScore: 80, copyLength: 142 },
  { adId: "ad-029", headlineFormula: "Product + Specific Metric + Benefit", emotionalTriggers: ["fear", "trust", "authority"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 86, copyLength: 128 },
  { adId: "ad-030", headlineFormula: "Comparative Benefit + CTA", emotionalTriggers: ["trust", "aspiration", "curiosity"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 52, copyLength: 116 },

  { adId: "ad-031", headlineFormula: "Number + Aggregation + Brand", emotionalTriggers: ["aspiration", "scarcity", "fomo"], ctaType: "click", sentiment: "positive", uniquenessScore: 61, copyLength: 138 },
  { adId: "ad-032", headlineFormula: "Metaphor + CTA", emotionalTriggers: ["curiosity", "aspiration", "social_proof"], ctaType: "click", sentiment: "positive", uniquenessScore: 88, copyLength: 126 },
  { adId: "ad-033", headlineFormula: "Brand + Feature + Action", emotionalTriggers: ["aspiration", "curiosity", "urgency"], ctaType: "click", sentiment: "positive", uniquenessScore: 70, copyLength: 119 },
  { adId: "ad-034", headlineFormula: "Audience + Offer + Price Anchor", emotionalTriggers: ["exclusivity", "scarcity", "aspiration"], ctaType: "click", sentiment: "positive", uniquenessScore: 65, copyLength: 131 },
  { adId: "ad-035", headlineFormula: "Problem + Contrast", emotionalTriggers: ["fear", "curiosity", "trust"], ctaType: "learn_more", sentiment: "neutral", uniquenessScore: 78, copyLength: 143 },
  { adId: "ad-036", headlineFormula: "Product + Use Case + Audience", emotionalTriggers: ["aspiration", "curiosity", "authority"], ctaType: "click", sentiment: "positive", uniquenessScore: 72, copyLength: 115 },

  { adId: "ad-037", headlineFormula: "Action + Action + Brand", emotionalTriggers: ["aspiration", "trust", "social_proof"], ctaType: "click", sentiment: "positive", uniquenessScore: 63, copyLength: 129 },
  { adId: "ad-038", headlineFormula: "Timeframe + Benefit + Brand", emotionalTriggers: ["urgency", "aspiration", "curiosity"], ctaType: "click", sentiment: "positive", uniquenessScore: 71, copyLength: 118 },
  { adId: "ad-039", headlineFormula: "Product + Benefit + Feature", emotionalTriggers: ["aspiration", "trust", "social_proof"], ctaType: "click", sentiment: "positive", uniquenessScore: 67, copyLength: 134 },
  { adId: "ad-040", headlineFormula: "Product Feature + Audience Benefit", emotionalTriggers: ["authority", "trust", "aspiration"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 82, copyLength: 122 },
  { adId: "ad-041", headlineFormula: "Comparison + Social Proof", emotionalTriggers: ["fomo", "curiosity", "trust"], ctaType: "click", sentiment: "neutral", uniquenessScore: 59, copyLength: 137 },
  { adId: "ad-042", headlineFormula: "Event + Urgency", emotionalTriggers: ["fomo", "scarcity", "social_proof"], ctaType: "subscribe", sentiment: "positive", uniquenessScore: 84, copyLength: 120 },

  { adId: "ad-043", headlineFormula: "Brand Tagline + Feature", emotionalTriggers: ["authority", "trust", "aspiration"], ctaType: "click", sentiment: "positive", uniquenessScore: 58, copyLength: 126 },
  { adId: "ad-044", headlineFormula: "Problem + Contrast + Solution", emotionalTriggers: ["fear", "curiosity", "aspiration"], ctaType: "click", sentiment: "positive", uniquenessScore: 74, copyLength: 138 },
  { adId: "ad-045", headlineFormula: "Audience Segment + Feature", emotionalTriggers: ["authority", "exclusivity", "trust"], ctaType: "click", sentiment: "positive", uniquenessScore: 67, copyLength: 141 },
  { adId: "ad-046", headlineFormula: "Brand + Feature + Benefit", emotionalTriggers: ["curiosity", "aspiration", "trust"], ctaType: "click", sentiment: "positive", uniquenessScore: 79, copyLength: 130 },
  { adId: "ad-047", headlineFormula: "Comparison + Audience", emotionalTriggers: ["curiosity", "fomo", "trust"], ctaType: "learn_more", sentiment: "neutral", uniquenessScore: 62, copyLength: 143 },
  { adId: "ad-048", headlineFormula: "Product Feature + Benefit", emotionalTriggers: ["aspiration", "curiosity", "trust"], ctaType: "click", sentiment: "positive", uniquenessScore: 71, copyLength: 117 },
  { adId: "ad-049", headlineFormula: "Content Type + Audience + Authority", emotionalTriggers: ["authority", "curiosity", "social_proof"], ctaType: "download", sentiment: "neutral", uniquenessScore: 85, copyLength: 153 },

  { adId: "ad-050", headlineFormula: "Brand + Feature + Price Anchor", emotionalTriggers: ["trust", "aspiration", "scarcity"], ctaType: "click", sentiment: "positive", uniquenessScore: 76, copyLength: 139 },
  { adId: "ad-051", headlineFormula: "Action + Number + Brand", emotionalTriggers: ["social_proof", "authority", "aspiration"], ctaType: "click", sentiment: "positive", uniquenessScore: 68, copyLength: 128 },
  { adId: "ad-052", headlineFormula: "Product Name + Category", emotionalTriggers: ["aspiration", "authority", "trust"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 64, copyLength: 122 },
  { adId: "ad-053", headlineFormula: "Product + Transformation + Metric", emotionalTriggers: ["aspiration", "authority", "trust"], ctaType: "demo", sentiment: "positive", uniquenessScore: 82, copyLength: 136 },
  { adId: "ad-054", headlineFormula: "Audience Segment + Offer + Discount", emotionalTriggers: ["exclusivity", "scarcity", "trust"], ctaType: "click", sentiment: "positive", uniquenessScore: 55, copyLength: 126 },
  { adId: "ad-055", headlineFormula: "Product + Transformation", emotionalTriggers: ["aspiration", "curiosity", "trust"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 73, copyLength: 131 },
  { adId: "ad-056", headlineFormula: "Content Type + Year + Topic", emotionalTriggers: ["curiosity", "authority", "fomo"], ctaType: "download", sentiment: "neutral", uniquenessScore: 78, copyLength: 119 },

  { adId: "ad-057", headlineFormula: "Action + Outcome + Brand", emotionalTriggers: ["aspiration", "trust", "curiosity"], ctaType: "click", sentiment: "positive", uniquenessScore: 72, copyLength: 143 },
  { adId: "ad-058", headlineFormula: "Brand + Audience Benefit + Social Proof", emotionalTriggers: ["social_proof", "trust", "aspiration"], ctaType: "click", sentiment: "positive", uniquenessScore: 66, copyLength: 137 },
  { adId: "ad-059", headlineFormula: "Replacement + Competitor + Brand", emotionalTriggers: ["curiosity", "aspiration", "trust"], ctaType: "demo", sentiment: "neutral", uniquenessScore: 58, copyLength: 126 },
  { adId: "ad-060", headlineFormula: "Authority Social Proof + Benefit", emotionalTriggers: ["social_proof", "authority", "curiosity"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 88, copyLength: 148 },
  { adId: "ad-061", headlineFormula: "Brand + Feature + Audience Benefit", emotionalTriggers: ["aspiration", "curiosity", "urgency"], ctaType: "click", sentiment: "positive", uniquenessScore: 70, copyLength: 121 },

  { adId: "ad-062", headlineFormula: "Problem Elimination + Brand", emotionalTriggers: ["fear", "aspiration", "trust"], ctaType: "click", sentiment: "positive", uniquenessScore: 61, copyLength: 118 },
  { adId: "ad-063", headlineFormula: "Action + Metric + Brand", emotionalTriggers: ["social_proof", "authority", "aspiration"], ctaType: "click", sentiment: "positive", uniquenessScore: 74, copyLength: 133 },
  { adId: "ad-064", headlineFormula: "Brand + Feature + Use Case", emotionalTriggers: ["aspiration", "trust", "authority"], ctaType: "click", sentiment: "positive", uniquenessScore: 68, copyLength: 127 },
  { adId: "ad-065", headlineFormula: "Problem + Urgency Stat", emotionalTriggers: ["fear", "urgency", "fomo"], ctaType: "click", sentiment: "negative", uniquenessScore: 83, copyLength: 141 },
  { adId: "ad-066", headlineFormula: "Product Feature + Benefit", emotionalTriggers: ["curiosity", "trust", "aspiration"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 76, copyLength: 130 },

  { adId: "ad-067", headlineFormula: "Product + AI + Brand", emotionalTriggers: ["authority", "curiosity", "aspiration"], ctaType: "demo", sentiment: "positive", uniquenessScore: 80, copyLength: 124 },
  { adId: "ad-068", headlineFormula: "Quantified Benefit + Brand", emotionalTriggers: ["aspiration", "authority", "trust"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 75, copyLength: 137 },
  { adId: "ad-069", headlineFormula: "Comparison + Reason", emotionalTriggers: ["curiosity", "fomo", "trust"], ctaType: "learn_more", sentiment: "neutral", uniquenessScore: 64, copyLength: 145 },
  { adId: "ad-070", headlineFormula: "Content + Year + Authority", emotionalTriggers: ["curiosity", "authority", "trust"], ctaType: "download", sentiment: "neutral", uniquenessScore: 79, copyLength: 118 },
  { adId: "ad-071", headlineFormula: "Feature + Audience Benefit + Result", emotionalTriggers: ["aspiration", "fear", "trust"], ctaType: "demo", sentiment: "positive", uniquenessScore: 84, copyLength: 143 },
  { adId: "ad-072", headlineFormula: "Audience + Discount + Offer", emotionalTriggers: ["exclusivity", "scarcity", "aspiration"], ctaType: "click", sentiment: "positive", uniquenessScore: 62, copyLength: 128 },

  { adId: "ad-073", headlineFormula: "Category + Result + Brand", emotionalTriggers: ["aspiration", "authority", "curiosity"], ctaType: "demo", sentiment: "positive", uniquenessScore: 71, copyLength: 138 },
  { adId: "ad-074", headlineFormula: "Problem + Contrast", emotionalTriggers: ["fear", "aspiration", "curiosity"], ctaType: "click", sentiment: "negative", uniquenessScore: 77, copyLength: 125 },
  { adId: "ad-075", headlineFormula: "Brand + Feature + Benefit", emotionalTriggers: ["curiosity", "trust", "aspiration"], ctaType: "demo", sentiment: "positive", uniquenessScore: 82, copyLength: 132 },
  { adId: "ad-076", headlineFormula: "Product Name + ABM + Feature", emotionalTriggers: ["exclusivity", "authority", "aspiration"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 86, copyLength: 117 },
  { adId: "ad-077", headlineFormula: "Metaphor + Stat + Solution", emotionalTriggers: ["fear", "aspiration", "social_proof"], ctaType: "click", sentiment: "positive", uniquenessScore: 79, copyLength: 136 },

  { adId: "ad-078", headlineFormula: "Brand + Feature + Audience Goal", emotionalTriggers: ["aspiration", "trust", "authority"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 74, copyLength: 128 },
  { adId: "ad-079", headlineFormula: "Brand + Feature + Benefit", emotionalTriggers: ["aspiration", "trust", "curiosity"], ctaType: "click", sentiment: "positive", uniquenessScore: 70, copyLength: 117 },
  { adId: "ad-080", headlineFormula: "Brand + Feature + Simplicity", emotionalTriggers: ["aspiration", "trust", "authority"], ctaType: "click", sentiment: "positive", uniquenessScore: 65, copyLength: 122 },
  { adId: "ad-081", headlineFormula: "Brand + Feature + Qualifier", emotionalTriggers: ["curiosity", "aspiration", "trust"], ctaType: "click", sentiment: "positive", uniquenessScore: 73, copyLength: 115 },
  { adId: "ad-082", headlineFormula: "Brand + Product + Scale Signal", emotionalTriggers: ["aspiration", "social_proof", "authority"], ctaType: "click", sentiment: "positive", uniquenessScore: 68, copyLength: 131 },
  { adId: "ad-083", headlineFormula: "Brand + Product + Audience", emotionalTriggers: ["aspiration", "curiosity", "authority"], ctaType: "learn_more", sentiment: "positive", uniquenessScore: 81, copyLength: 123 },
  { adId: "ad-084", headlineFormula: "Brand + Feature + Benefit", emotionalTriggers: ["curiosity", "aspiration", "trust"], ctaType: "click", sentiment: "positive", uniquenessScore: 76, copyLength: 118 },
  { adId: "ad-085", headlineFormula: "Product + Result + Metric", emotionalTriggers: ["aspiration", "trust", "social_proof"], ctaType: "click", sentiment: "positive", uniquenessScore: 78, copyLength: 134 },
];
