import type { Keyword } from "../types";

export const KEYWORDS: readonly Keyword[] = [
  {
    id: "kw-001",
    keyword: "project management software",
    searchVolume: 450000,
    cpcAvg: 8.42,
    cpcLow: 4.20,
    cpcHigh: 14.80,
    competitionLevel: "high",
    intent: "commercial",
    topCompetitors: ["asana.com", "monday.com", "notion.so", "airtable.com"],
  },
  {
    id: "kw-002",
    keyword: "crm for small business",
    searchVolume: 165000,
    cpcAvg: 9.75,
    cpcLow: 5.50,
    cpcHigh: 16.20,
    competitionLevel: "high",
    intent: "commercial",
    topCompetitors: ["hubspot.com", "pipedrive.com", "zoho.com", "salesforce.com"],
  },
  {
    id: "kw-003",
    keyword: "team collaboration tools",
    searchVolume: 90500,
    cpcAvg: 7.30,
    cpcLow: 3.80,
    cpcHigh: 12.50,
    competitionLevel: "high",
    intent: "commercial",
    topCompetitors: ["slack.com", "notion.so", "asana.com", "zoom.us"],
  },
  {
    id: "kw-004",
    keyword: "how to start an online store",
    searchVolume: 320000,
    cpcAvg: 3.15,
    cpcLow: 1.20,
    cpcHigh: 6.80,
    competitionLevel: "medium",
    intent: "informational",
    topCompetitors: ["shopify.com", "wix.com", "squarespace.com"],
  },
  {
    id: "kw-005",
    keyword: "accept payments online",
    searchVolume: 74000,
    cpcAvg: 11.20,
    cpcLow: 6.00,
    cpcHigh: 18.40,
    competitionLevel: "high",
    intent: "commercial",
    topCompetitors: ["stripe.com", "paypal.com", "square.com", "braintree.com"],
  },
  {
    id: "kw-006",
    keyword: "meeting scheduling app",
    searchVolume: 40200,
    cpcAvg: 5.85,
    cpcLow: 2.90,
    cpcHigh: 9.50,
    competitionLevel: "medium",
    intent: "commercial",
    topCompetitors: ["calendly.com", "doodle.com", "acuityscheduling.com"],
  },
  {
    id: "kw-007",
    keyword: "customer support software",
    searchVolume: 135000,
    cpcAvg: 12.40,
    cpcLow: 7.20,
    cpcHigh: 19.60,
    competitionLevel: "high",
    intent: "commercial",
    topCompetitors: ["intercom.com", "zendesk.com", "freshdesk.com", "hubspot.com"],
  },
  {
    id: "kw-008",
    keyword: "video conferencing software",
    searchVolume: 210000,
    cpcAvg: 6.90,
    cpcLow: 3.40,
    cpcHigh: 11.80,
    competitionLevel: "high",
    intent: "commercial",
    topCompetitors: ["zoom.us", "microsoft.com", "google.com", "webex.com"],
  },
  {
    id: "kw-009",
    keyword: "design tool for teams",
    searchVolume: 28600,
    cpcAvg: 4.55,
    cpcLow: 2.10,
    cpcHigh: 8.20,
    competitionLevel: "medium",
    intent: "commercial",
    topCompetitors: ["figma.com", "sketch.com", "adobe.com", "canva.com"],
  },
  {
    id: "kw-010",
    keyword: "no-code database app",
    searchVolume: 18400,
    cpcAvg: 6.20,
    cpcLow: 3.00,
    cpcHigh: 10.80,
    competitionLevel: "medium",
    intent: "commercial",
    topCompetitors: ["airtable.com", "notion.so", "coda.io", "smartsheet.com"],
  },
  {
    id: "kw-011",
    keyword: "slack alternative",
    searchVolume: 55000,
    cpcAvg: 8.80,
    cpcLow: 4.50,
    cpcHigh: 14.20,
    competitionLevel: "high",
    intent: "commercial",
    topCompetitors: ["slack.com", "discord.com", "teams.microsoft.com", "notion.so"],
  },
  {
    id: "kw-012",
    keyword: "email marketing automation",
    searchVolume: 180000,
    cpcAvg: 10.30,
    cpcLow: 5.80,
    cpcHigh: 17.40,
    competitionLevel: "high",
    intent: "commercial",
    topCompetitors: ["hubspot.com", "mailchimp.com", "activecampaign.com", "klaviyo.com"],
  },
  {
    id: "kw-013",
    keyword: "ecommerce platform comparison",
    searchVolume: 42000,
    cpcAvg: 4.10,
    cpcLow: 1.80,
    cpcHigh: 7.50,
    competitionLevel: "medium",
    intent: "informational",
    topCompetitors: ["shopify.com", "bigcommerce.com", "woocommerce.com"],
  },
  {
    id: "kw-014",
    keyword: "payment processing fees",
    searchVolume: 95000,
    cpcAvg: 7.60,
    cpcLow: 4.00,
    cpcHigh: 13.20,
    competitionLevel: "high",
    intent: "informational",
    topCompetitors: ["stripe.com", "square.com", "paypal.com", "adyen.com"],
  },
  {
    id: "kw-015",
    keyword: "buy project management software",
    searchVolume: 12800,
    cpcAvg: 14.20,
    cpcLow: 8.50,
    cpcHigh: 22.00,
    competitionLevel: "high",
    intent: "transactional",
    topCompetitors: ["asana.com", "monday.com", "clickup.com", "airtable.com"],
  },
  {
    id: "kw-016",
    keyword: "best crm software 2026",
    searchVolume: 88000,
    cpcAvg: 11.50,
    cpcLow: 6.20,
    cpcHigh: 18.80,
    competitionLevel: "high",
    intent: "informational",
    topCompetitors: ["hubspot.com", "salesforce.com", "pipedrive.com", "zoho.com"],
  },
  {
    id: "kw-017",
    keyword: "slack pricing",
    searchVolume: 68000,
    cpcAvg: 9.40,
    cpcLow: 5.10,
    cpcHigh: 15.60,
    competitionLevel: "high",
    intent: "navigational",
    topCompetitors: ["slack.com", "teams.microsoft.com", "discord.com"],
  },
  {
    id: "kw-018",
    keyword: "notion vs confluence",
    searchVolume: 31000,
    cpcAvg: 5.20,
    cpcLow: 2.50,
    cpcHigh: 9.00,
    competitionLevel: "medium",
    intent: "informational",
    topCompetitors: ["notion.so", "atlassian.com", "coda.io"],
  },
  {
    id: "kw-019",
    keyword: "try shopify free",
    searchVolume: 24000,
    cpcAvg: 2.80,
    cpcLow: 1.20,
    cpcHigh: 5.40,
    competitionLevel: "medium",
    intent: "transactional",
    topCompetitors: ["shopify.com", "wix.com", "bigcommerce.com"],
  },
  {
    id: "kw-020",
    keyword: "figma free plan",
    searchVolume: 19500,
    cpcAvg: 3.70,
    cpcLow: 1.60,
    cpcHigh: 6.40,
    competitionLevel: "low",
    intent: "transactional",
    topCompetitors: ["figma.com", "sketch.com", "penpot.app"],
  },
  {
    id: "kw-021",
    keyword: "what is a crm",
    searchVolume: 390000,
    cpcAvg: 4.90,
    cpcLow: 2.10,
    cpcHigh: 8.60,
    competitionLevel: "medium",
    intent: "informational",
    topCompetitors: ["hubspot.com", "salesforce.com", "zoho.com"],
  },
  {
    id: "kw-022",
    keyword: "zoom alternative free",
    searchVolume: 47000,
    cpcAvg: 5.10,
    cpcLow: 2.40,
    cpcHigh: 8.90,
    competitionLevel: "medium",
    intent: "commercial",
    topCompetitors: ["zoom.us", "google.com", "microsoft.com", "jitsi.org"],
  },
  {
    id: "kw-023",
    keyword: "sign up for hubspot",
    searchVolume: 14200,
    cpcAvg: 7.20,
    cpcLow: 3.80,
    cpcHigh: 12.40,
    competitionLevel: "medium",
    intent: "transactional",
    topCompetitors: ["hubspot.com", "mailchimp.com", "activecampaign.com"],
  },
  {
    id: "kw-024",
    keyword: "chatbot for website",
    searchVolume: 62000,
    cpcAvg: 8.60,
    cpcLow: 4.30,
    cpcHigh: 14.00,
    competitionLevel: "high",
    intent: "commercial",
    topCompetitors: ["drift.com", "intercom.com", "tidio.com", "hubspot.com"],
  },
  {
    id: "kw-025",
    keyword: "recurring billing software",
    searchVolume: 22000,
    cpcAvg: 9.80,
    cpcLow: 5.20,
    cpcHigh: 16.50,
    competitionLevel: "high",
    intent: "commercial",
    topCompetitors: ["stripe.com", "chargebee.com", "recurly.com"],
  },
  {
    id: "kw-026",
    keyword: "remote team management tools",
    searchVolume: 38500,
    cpcAvg: 6.40,
    cpcLow: 3.10,
    cpcHigh: 10.90,
    competitionLevel: "medium",
    intent: "commercial",
    topCompetitors: ["asana.com", "slack.com", "zoom.us", "notion.so"],
  },
  {
    id: "kw-027",
    keyword: "airtable pricing",
    searchVolume: 29000,
    cpcAvg: 4.30,
    cpcLow: 2.00,
    cpcHigh: 7.60,
    competitionLevel: "low",
    intent: "navigational",
    topCompetitors: ["airtable.com", "smartsheet.com", "monday.com"],
  },
  {
    id: "kw-028",
    keyword: "intercom vs zendesk",
    searchVolume: 16800,
    cpcAvg: 10.20,
    cpcLow: 5.80,
    cpcHigh: 16.40,
    competitionLevel: "high",
    intent: "informational",
    topCompetitors: ["intercom.com", "zendesk.com", "freshdesk.com"],
  },
  {
    id: "kw-029",
    keyword: "online store builder",
    searchVolume: 128000,
    cpcAvg: 3.90,
    cpcLow: 1.60,
    cpcHigh: 7.20,
    competitionLevel: "medium",
    intent: "commercial",
    topCompetitors: ["shopify.com", "wix.com", "squarespace.com", "bigcommerce.com"],
  },
  {
    id: "kw-030",
    keyword: "calendly download",
    searchVolume: 8900,
    cpcAvg: 2.10,
    cpcLow: 0.80,
    cpcHigh: 4.20,
    competitionLevel: "low",
    intent: "navigational",
    topCompetitors: ["calendly.com", "doodle.com"],
  },
];
